#############################################################################
# Makefile for building: picturewall
# Generated by qmake (2.01a) (Qt 4.5.0) on: Wed Apr 15 23:02:33 2009
# Project:  picturewall.pro
# Template: subdirs
# Command: /usr/local/Trolltech/Qt-4.5.0/bin/qmake -unix -o Makefile picturewall.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/Trolltech/Qt-4.5.0/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) src.pro -unix -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) src.pro -unix -o $(MAKEFILE)
sub-src: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src/$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: picturewall.pro  /usr/local/Trolltech/Qt-4.5.0/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.5.0/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile picturewall.pro
/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.5.0/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile picturewall.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

