#############################################################################
# Makefile for building: PictureWall
# Generated by qmake (2.01a) (Qt 4.4.3) on: Sat Apr 18 11:25:40 2009
# Project:  PictureWall.pro
# Template: subdirs
# Command: d:\InstalledQt\qt-win-opensource-src-4.4.3\bin\qmake.exe -win32 -o Makefile PictureWall.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = d:\InstalledQt\qt-win-opensource-src-4.4.3\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-src

src\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) src.pro -win32 -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src\ $(MKDIR) src\ 
	cd src\ && $(QMAKE) src.pro -win32 -o $(MAKEFILE)
sub-src: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src\$(MAKEFILE) FORCE
	cd src\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: PictureWall.pro  d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\default\qmake.conf d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\qconfig.pri \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\qt_functions.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\qt_config.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\exclusive_builds.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\default_pre.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\default_pre.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\debug.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\debug_and_release.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\default_post.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\thread.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\qt.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\moc.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\warn_on.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\rtti.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\exceptions.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\stl.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\shared.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\embed_manifest_exe.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\embed_manifest_dll.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\windows.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\resources.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\uic.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\yacc.prf \
		d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\lex.prf
	$(QMAKE) -win32 -o Makefile PictureWall.pro
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\qconfig.pri:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\qt_functions.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\qt_config.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\exclusive_builds.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\default_pre.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\default_pre.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\debug.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\debug_and_release.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\default_post.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\thread.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\qt.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\moc.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\warn_on.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\rtti.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\exceptions.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\stl.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\shared.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\embed_manifest_exe.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\embed_manifest_dll.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\win32\windows.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\resources.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\uic.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\yacc.prf:
d:\InstalledQt\qt-win-opensource-src-4.4.3\mkspecs\features\lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -win32 -o Makefile PictureWall.pro

qmake_all: sub-src-qmake_all FORCE

make_default: sub-src-make_default FORCE
make_first: sub-src-make_first FORCE
all: sub-src-all FORCE
clean: sub-src-clean FORCE
distclean: sub-src-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-sub_Debug: src\\$(MAKEFILE)
	cd src\ && $(MAKE) debug
debug: sub-src-sub_Debug

sub-src-sub_Release: src\\$(MAKEFILE)
	cd src\ && $(MAKE) release
release: sub-src-sub_Release

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

